### PR TITLE
Fix fonts

### PR DESCRIPTION
**Pull request by JoaquinTrinanes**
Some glyphs are missing:
image

### CODE REVIEW

**Comment by JoaquinTrinanes** [comment]
Hey @MatsThieme! If you look at the two commits you'll see that I used two different methods to load the fonts. They should be more or less equivalent, but I think Nextjs' official one might be faster and integrates better with tailwind :)

**Comment by MatsThieme** [comment]
@JoaquinTrinanes Looks good, do you know why the linter failed?

**Comment by MatsThieme** [comment]
Hey @JoaquinTrinanes, can you please check the linter error?

**Comment by JoaquinTrinanes** [comment]
Oops, I missed the first comment. I'll check it first thing Monday!

**Comment by JoaquinTrinanes** [comment]
@MatsThieme apparently the errors were caused by using and old pnpm version (or more likely an old pnpm install action?). I bumped them and the lint action succeeded!

**Review by MatsThieme — APPROVED** [review]

**Review by MatsThieme — APPROVED** [review]
Looks great! Thank you for fixing the lint job!

**Pull request merged**
